In [1]:
import pandas as pd 
import numpy as np

### Step 1. Data Collection and initial Exploration

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

#### Dataset Overview

In [4]:
df.shape

(50000, 2)

In [5]:
print(df.columns)

Index(['review', 'sentiment'], dtype='object')

#### Dataset Information

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [8]:
# stastical summary 

df.describe(include='all')

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

#### check null values

In [9]:
print("Null Values:\n")
print(df.isnull().sum())

Null Values:

review       0
sentiment    0
dtype: int64

In [10]:
# there is no null values so we don't have to handlethem.

In [12]:
# check duplicate rows
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 418

In [13]:
# remove duplicate rows

df = df.drop_duplicates()

print("dataset shape after removing duplicates")

dataset shape after removing duplicates

In [16]:
# check sentiment distribution
print("Sentiment Distribution:\n")
print(df["sentiment"].value_counts())

Sentiment Distribution:

sentiment
positive    24884
negative    24698
Name: count, dtype: int64

In [17]:
# final dataset shape

print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (49582, 2)

#### Data preprocessing