In [8]:
import pandas as pd 
import numpy as np

### Step 1. Data Collection and initial Exploration

In [9]:
df = pd.read_csv("IMDB Dataset.csv")

In [10]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

#### Dataset Overview

In [11]:
df.shape

(50000, 2)

In [12]:
print(df.columns)

Index(['review', 'sentiment'], dtype='object')

#### Dataset Information

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [14]:
# stastical summary 

df.describe(include='all')

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

#### check null values

In [15]:
print("Null Values:\n")
print(df.isnull().sum())

Null Values:

review       0
sentiment    0
dtype: int64

In [16]:
# there is no null values so we don't have to handlethem.

In [17]:
# check duplicate rows
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 418

In [18]:
# remove duplicate rows

df = df.drop_duplicates()

print("dataset shape after removing duplicates")

dataset shape after removing duplicates

In [19]:
# check sentiment distribution
print("Sentiment Distribution:\n")
print(df["sentiment"].value_counts())

Sentiment Distribution:

sentiment
positive    24884
negative    24698
Name: count, dtype: int64

In [20]:
# final dataset shape

print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (49582, 2)

#### Data preprocessing

##### Import Libraries

In [21]:
pip install nltk

Requirement already satisfied: nltk in c:\users\saini\appdata\local\programs\python\python310\lib\site-packages (3.10.0)
Requirement already satisfied: defusedxml in c:\users\saini\appdata\local\programs\python\python310\lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\saini\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.4.1)
Requirement already satisfied: tqdm in c:\users\saini\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.68.4)
Requirement already satisfied: joblib in c:\users\saini\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\saini\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2026.7.10)
Requirement already satisfied: colorama in c:\users\saini\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\saini\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\saini\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [25]:
# making copy of review colunmn


df["clean_review"] = df["review"]

df[["review", "clean_review"]].head()

                                              review                                       clean_review
0  One of the other reviewers has mentioned that ...  One of the other reviewers has mentioned that ...
1  A wonderful little production. <br /><br />The...  A wonderful little production. <br /><br />The...
2  I thought this was a wonderful way to spend ti...  I thought this was a wonderful way to spend ti...
3  Basically there's a family where a little boy ...  Basically there's a family where a little boy ...
4  Petter Mattei's "Love in the Time of Money" is...  Petter Mattei's "Love in the Time of Money" is...

In [26]:
# Remove HTML tags

def remove_html(text):
    return re.sub(r"<.*?>", "", text)
    
df["clean_review"] = df["clean_review"].apply(remove_html)

df["clean_review"].head()

0    One of the other reviewers has mentioned that ...
1    A wonderful little production. The filming tec...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
Name: clean_review, dtype: object

In [ ]:
# remove urls

def remove_urls(text):
    return re.sub(r"http\")